name: Update AoC Stars
on:
  workflow_dispatch:
  #workflow_run:
  #  workflows: [ "Update AoC Badges" ]
  #  types:
  #    - completed
  #schedule:
  #  - cron: '26 14 1-25 12 *'  # Every 4 hours

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: TomW1605/advent-readme-stars@v1
        with:
          userId: 1200593
          leaderboardId: 965021
          sessionCookie: ${{ secrets.AOC_SESSION }}
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update AoC Stars